server:
  port: 80

dubbo:
  application:
    name: sample-microservice-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848

  scan:
    base-packages: mooon.service
  cloud:
    subscribed-services:


