server:
  port: 8081


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

  dashboard:
    init-parameters:
      A: 1
      B: 2

#hystrix.shareSecurityContext=true
#management.endpoints.web.exposure.include=hystrix.stream
##1.默认：（方法上记得要加上@HystrixCommand，否则无效）：
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=1000
##2.配置具体方法的超时时间
##hystrix.command.serverMethod.execution.isolation.thread.timeoutInMilliseconds=3000


#logging:
#  level:
#    root: info
#  pattern:
#    file: %date{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
#    console: %date{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n